import type { Metadata } from 'next';
import { Inter, Merriweather_Sans, Poppins, Sigmar_One } from 'next/font/google';
import './globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Header from './components/header';
import Profile from './components/profile';
import NavBar from './components/nav';

config.autoAddCss = false;

const poppins = Poppins({
	subsets: ['latin'],
	variable: '--font-poppins',
	weight: ['400', '500', '700'],
});

export const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
	weight: ['400', '600'],
});

export const merriWeatherSans = Merriweather_Sans({
	variable: '--font-merri-weather-sans',
	subsets: ['latin'],
	weight: ['400', '600'],
});

export const sigmaOne = Sigmar_One({
	variable: '--font-sigma-one',
	subsets: ['latin'],
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'Moshood',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${sigmaOne.variable} ${poppins.variable} ${inter.variable} ${merriWeatherSans.variable} antialiased bg-background`}
			>
				<Header />
				<main className="flex gap-12 max-w-11/12 mx-auto mb-12">
					<Profile />
					<section className="flex-1">{children}</section>
					<NavBar />
				</main>
			</body>
		</html>
	);
}
